# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin_V1.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LettuceMain(object):
    def setupUi(self, LettuceMain):
        LettuceMain.setObjectName("LettuceMain")
        LettuceMain.resize(557, 780)
        LettuceMain.setMinimumSize(QtCore.QSize(557, 780))
        LettuceMain.setMaximumSize(QtCore.QSize(557, 780))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LettuceMain.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LettuceMain)
        self.centralwidget.setObjectName("centralwidget")
        self.group_input = QtWidgets.QGroupBox(self.centralwidget)
        self.group_input.setGeometry(QtCore.QRect(10, 10, 531, 311))
        self.group_input.setObjectName("group_input")
        self.btn_loadImg = QtWidgets.QPushButton(self.group_input)
        self.btn_loadImg.setGeometry(QtCore.QRect(300, 40, 221, 41))
        self.btn_loadImg.setIconSize(QtCore.QSize(20, 20))
        self.btn_loadImg.setAutoDefault(True)
        self.btn_loadImg.setDefault(False)
        self.btn_loadImg.setObjectName("btn_loadImg")
        self.btn_measure = QtWidgets.QPushButton(self.group_input)
        self.btn_measure.setGeometry(QtCore.QRect(400, 150, 121, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Measure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_measure.setIcon(icon1)
        self.btn_measure.setObjectName("btn_measure")
        self.label_raw = ImageLabel(self.group_input)
        self.label_raw.setGeometry(QtCore.QRect(20, 40, 261, 261))
        self.label_raw.setText("")
        self.label_raw.setPixmap(QtGui.QPixmap(":/blank.png"))
        self.label_raw.setScaledContents(True)
        self.label_raw.setObjectName("label_raw")
        self.btn_rescale = QtWidgets.QPushButton(self.group_input)
        self.btn_rescale.setGeometry(QtCore.QRect(300, 260, 221, 31))
        self.btn_rescale.setObjectName("btn_rescale")
        self.btn_redo = QtWidgets.QPushButton(self.group_input)
        self.btn_redo.setGeometry(QtCore.QRect(480, 200, 41, 31))
        self.btn_redo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_redo.setIcon(icon2)
        self.btn_redo.setAutoDefault(False)
        self.btn_redo.setDefault(False)
        self.btn_redo.setFlat(False)
        self.btn_redo.setObjectName("btn_redo")
        self.num_pixels = QtWidgets.QSpinBox(self.group_input)
        self.num_pixels.setGeometry(QtCore.QRect(350, 200, 71, 31))
        self.num_pixels.setMinimum(1)
        self.num_pixels.setMaximum(9999)
        self.num_pixels.setProperty("value", 120)
        self.num_pixels.setObjectName("num_pixels")
        self.label_3 = QtWidgets.QLabel(self.group_input)
        self.label_3.setGeometry(QtCore.QRect(300, 200, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_3.setPalette(palette)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.group_input)
        self.label_9.setGeometry(QtCore.QRect(430, 200, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_9.setPalette(palette)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.btn_crop = QtWidgets.QPushButton(self.group_input)
        self.btn_crop.setGeometry(QtCore.QRect(300, 150, 91, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_crop.setIcon(icon3)
        self.btn_crop.setObjectName("btn_crop")
        self.label_6 = QtWidgets.QLabel(self.group_input)
        self.label_6.setGeometry(QtCore.QRect(300, 90, 141, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_6.setPalette(palette)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.num_DAS = QtWidgets.QSpinBox(self.group_input)
        self.num_DAS.setGeometry(QtCore.QRect(440, 90, 71, 31))
        self.num_DAS.setReadOnly(False)
        self.num_DAS.setMinimum(19)
        self.num_DAS.setMaximum(44)
        self.num_DAS.setObjectName("num_DAS")
        self.label_2 = QtWidgets.QLabel(self.group_input)
        self.label_2.setGeometry(QtCore.QRect(440, 120, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_2.setPalette(palette)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.group_processing = QtWidgets.QGroupBox(self.centralwidget)
        self.group_processing.setGeometry(QtCore.QRect(10, 330, 531, 311))
        self.group_processing.setAutoFillBackground(False)
        self.group_processing.setObjectName("group_processing")
        self.btn_seg = QtWidgets.QPushButton(self.group_processing)
        self.btn_seg.setGeometry(QtCore.QRect(300, 40, 221, 41))
        self.btn_seg.setIconSize(QtCore.QSize(16, 16))
        self.btn_seg.setObjectName("btn_seg")
        self.label_seg = ImageLabel(self.group_processing)
        self.label_seg.setGeometry(QtCore.QRect(20, 40, 261, 261))
        self.label_seg.setText("")
        self.label_seg.setPixmap(QtGui.QPixmap(":/blank.png"))
        self.label_seg.setScaledContents(True)
        self.label_seg.setObjectName("label_seg")
        self.btn_classify = QtWidgets.QPushButton(self.group_processing)
        self.btn_classify.setGeometry(QtCore.QRect(300, 90, 101, 31))
        self.btn_classify.setObjectName("btn_classify")
        self.comboBox_classify = QtWidgets.QComboBox(self.group_processing)
        self.comboBox_classify.setGeometry(QtCore.QRect(410, 90, 111, 31))
        self.comboBox_classify.setObjectName("comboBox_classify")
        self.comboBox_classify.addItem("")
        self.comboBox_classify.addItem("")
        self.comboBox_classify.addItem("")
        self.comboBox_classify.addItem("")
        self.comboBox_classify.addItem("")
        self.comboBox_classify.addItem("")
        self.btn_reset = QtWidgets.QPushButton(self.group_processing)
        self.btn_reset.setGeometry(QtCore.QRect(390, 209, 131, 31))
        self.btn_reset.setObjectName("btn_reset")
        self.label_8 = QtWidgets.QLabel(self.group_processing)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(300, 180, 101, 20))
        self.label_8.setObjectName("label_8")
        self.num_fakeNum = QtWidgets.QSpinBox(self.group_processing)
        self.num_fakeNum.setGeometry(QtCore.QRect(300, 210, 81, 31))
        self.num_fakeNum.setReadOnly(False)
        self.num_fakeNum.setMaximum(0)
        self.num_fakeNum.setObjectName("num_fakeNum")
        self.btn_generate = QtWidgets.QPushButton(self.group_processing)
        self.btn_generate.setGeometry(QtCore.QRect(300, 250, 221, 41))
        self.btn_generate.setObjectName("btn_generate")
        self.group_yield = QtWidgets.QGroupBox(self.centralwidget)
        self.group_yield.setGeometry(QtCore.QRect(10, 650, 531, 101))
        self.group_yield.setObjectName("group_yield")
        self.btn_yield = QtWidgets.QPushButton(self.group_yield)
        self.btn_yield.setGeometry(QtCore.QRect(300, 50, 221, 41))
        self.btn_yield.setIconSize(QtCore.QSize(16, 16))
        self.btn_yield.setObjectName("btn_yield")
        self.num_yield = QtWidgets.QLCDNumber(self.group_yield)
        self.num_yield.setGeometry(QtCore.QRect(20, 50, 121, 41))
        self.num_yield.setDigitCount(5)
        self.num_yield.setProperty("value", 9999.0)
        self.num_yield.setObjectName("num_yield")
        self.num_r2 = QtWidgets.QLCDNumber(self.group_yield)
        self.num_r2.setGeometry(QtCore.QRect(160, 50, 121, 41))
        self.num_r2.setSmallDecimalPoint(True)
        self.num_r2.setDigitCount(3)
        self.num_r2.setProperty("value", 0.99)
        self.num_r2.setObjectName("num_r2")
        self.label_10 = QtWidgets.QLabel(self.group_yield)
        self.label_10.setEnabled(True)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 101, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.group_yield)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(160, 30, 71, 21))
        self.label_11.setObjectName("label_11")
        self.btn_hint = QtWidgets.QPushButton(self.group_yield)
        self.btn_hint.setGeometry(QtCore.QRect(510, 10, 21, 21))
        self.btn_hint.setAutoFillBackground(False)
        self.btn_hint.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Hint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hint.setIcon(icon4)
        self.btn_hint.setIconSize(QtCore.QSize(16, 20))
        self.btn_hint.setAutoRepeat(False)
        self.btn_hint.setAutoDefault(False)
        self.btn_hint.setDefault(False)
        self.btn_hint.setFlat(True)
        self.btn_hint.setObjectName("btn_hint")
        LettuceMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LettuceMain)
        self.statusbar.setObjectName("statusbar")
        LettuceMain.setStatusBar(self.statusbar)

        self.retranslateUi(LettuceMain)
        QtCore.QMetaObject.connectSlotsByName(LettuceMain)

    def retranslateUi(self, LettuceMain):
        _translate = QtCore.QCoreApplication.translate
        LettuceMain.setWindowTitle(_translate("LettuceMain", "5 Days Lettuce"))
        self.group_input.setTitle(_translate("LettuceMain", "Input"))
        self.btn_loadImg.setText(_translate("LettuceMain", "Load Image"))
        self.btn_measure.setText(_translate("LettuceMain", "Measure"))
        self.btn_rescale.setText(_translate("LettuceMain", "Rescale"))
        self.label_3.setText(_translate("LettuceMain", "10cm="))
        self.label_9.setText(_translate("LettuceMain", "pixels"))
        self.btn_crop.setText(_translate("LettuceMain", "Crop"))
        self.label_6.setText(_translate("LettuceMain", "Days After Planting:"))
        self.label_2.setText(_translate("LettuceMain", "19-44days"))
        self.group_processing.setTitle(_translate("LettuceMain", "Growth prediction"))
        self.btn_seg.setText(_translate("LettuceMain", "Segmentation"))
        self.btn_classify.setText(_translate("LettuceMain", "Classify"))
        self.comboBox_classify.setItemText(0, _translate("LettuceMain", "Butterhead"))
        self.comboBox_classify.setItemText(1, _translate("LettuceMain", "Crisphead"))
        self.comboBox_classify.setItemText(2, _translate("LettuceMain", "Looseleaf"))
        self.comboBox_classify.setItemText(3, _translate("LettuceMain", "Romaine"))
        self.comboBox_classify.setItemText(4, _translate("LettuceMain", "Stem"))
        self.comboBox_classify.setItemText(5, _translate("LettuceMain", "Wildlettuce"))
        self.btn_reset.setText(_translate("LettuceMain", "Reset"))
        self.label_8.setText(_translate("LettuceMain", "Generated Times"))
        self.btn_generate.setText(_translate("LettuceMain", "5 Days Later"))
        self.group_yield.setTitle(_translate("LettuceMain", "Yield prediction"))
        self.btn_yield.setText(_translate("LettuceMain", "Yield Prediction"))
        self.label_10.setText(_translate("LettuceMain", "Yield (g):"))
        self.label_11.setText(_translate("LettuceMain", "Accuracy:"))
from imagelabel import ImageLabel
import resource_file_rc
